In [3]:
import numpy as np
#create random vector of size 20 with float values between 1 and 20
x = np.random.uniform(1,20,20)
#Reshape array to 4 by 5
matrix = x.reshape(4,5)
print(matrix)
#Replace max in each row by 0 using np.where()
matrix = np.where(matrix == np.max(matrix, axis=1 ,keepdims=True),0,matrix)
print(matrix)

[[ 2.58980278  6.72877271 11.64488    12.7190762  10.41606265]
 [ 4.23740574  4.10719584  2.23907936  1.8941161   2.79597502]
 [11.55886423 12.14923178  5.94108837  4.40264544 12.80449461]
 [ 3.54114218  6.53737812 17.84555532 16.66465677 12.74463565]]
[[ 2.58980278  6.72877271 11.64488     0.         10.41606265]
 [ 0.          4.10719584  2.23907936  1.8941161   2.79597502]
 [11.55886423 12.14923178  5.94108837  4.40264544  0.        ]
 [ 3.54114218  6.53737812  0.         16.66465677 12.74463565]]
